version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb_container    
    env_file:
      - my_env_file.env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: unless-stopped

  wordpress:
    build:
     context: ./requirements/wordpress
    container_name: wordpress_container
    env_file:
      - my_env_file.env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx_container
    env_file:
      - my_env_file.env
    ports:
      - "443:443"
    volumes:
     - wordpress_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: always

networks:
  inception_network:
volumes:
  mariadb_data:
   driver: local
   driver_opts:
    type: none
    device: /home/ruva/data/mariadb
    o: bind
  wordpress_data:
   driver: local
   driver_opts:
    type: none
    device: /home/ruva/data/wordpress
    o: bind
